from all_imports_packages import *


class UnitTable:
    def __init__(self):
        self.unit_power = {
            # Zerg
            OVERLORD: 0.001,
            BANELING: 100,
            ZERGLING: 25,
            ZERGLINGBURROWED: 25,
            HYDRALISK: 200,
            HYDRALISKBURROWED: 200,
            MUTALISK: 300,
            ULTRALISK: 700,
            ROACH: 125,
            ROACHBURROWED: 125,
            INFESTOR: 400,
            QUEEN: 150,
            OVERSEER: 0.001,
            RAVAGER: 300,
            LURKERMP: 450,
            LURKERMPBURROWED: 450,
            CORRUPTOR: 350,
            VIPER: 500,
            BROODLORD: 800,
            SPINECRAWLER: 100,
            SPINECRAWLERUPROOTED: 100,
            SPORECRAWLER: 75,
            SPORECRAWLERUPROOTED: 75,
            OVERLORDTRANSPORT: 0.001,
            INFESTORTERRAN: 5,
            CHANGELINGZERGLING: 5,
            BROODLING: 4,
            DRONE: 50,
            EXTRACTOR: 0.001,
            HATCHERY: 0.001,
            EGG: 0.001,
            LARVA: 0.001,
            CREEPTUMOR: 0.001,
            CREEPTUMORBURROWED: 0.001,
            LOCUSTMP: 75,
            SWARMHOSTMP: 300,
            SWARMHOSTBURROWEDMP: 300,

            # Protoss
            ZEALOT: 100,
            STALKER: 225,
            ADEPT: 150,
            SENTRY: 120,
            IMMORTAL: 475,
            WARPPRISM: 0.001,
            WARPPRISMPHASING: 0.001,
            VOIDRAY: 550,
            PHOENIX: 350,
            COLOSSUS: 700,
            TEMPEST: 600,
            HIGHTEMPLAR: 350,
            DISRUPTOR: 450,
            DARKTEMPLAR: 375,
            OBSERVER: 0.001,
            ARCHON: 700,
            PHOTONCANNON: 150,
            ORACLE: 450,
            CARRIER: 850,
            MOTHERSHIP: 1200,
            PROBE: 0.001,
            INTERCEPTOR: 0.001,

            # Terran
            COMMANDCENTER: 0.001,
            BUNKER: 350,
            PLANETARYFORTRESS: 850,
            MARINE: 50,
            REAPER: 150,
            MARAUDER: 150,
            GHOST: 375,
            HELLION: 100,
            HELLIONTANK: 100,
            WIDOWMINEBURROWED: 125,
            WIDOWMINE: 125,
            CYCLONE: 350,
            SIEGETANK: 400,
            SIEGETANKSIEGED: 400,
            THOR: 700,
            THORAP: 700,
            VIKING: 300,
            VIKINGFIGHTER: 300,
            VIKINGASSAULT: 300,
            MEDIVAC: 300,
            LIBERATOR: 450,
            LIBERATORAG: 450,
            RAVEN: 500,
            BANSHEE: 350,
            BATTLECRUISER: 1000,
            MISSILETURRET: 100,
            AUTOTURRET: 5,
            KD8CHARGE: 0.001,
            SCV: 0.001,
        }
        self.units_counter_by = {
            # Zerg
            BANELING: [(ROACH, 1 / 2), (LURKERMP, 1 / 5)],
            ZERGLING: [(ZERGLING, 1), (LURKERMP, 1 / 5), (BANELING, 1 / 2), (ROACH, 1 / 2)],
            ZERGLINGBURROWED: [(OVERSEER, 1 / 20), (LURKERMP, 1 / 5), (BANELING, 1 / 2), (ROACH, 1 / 2)],
            HYDRALISK: [(BROODLORD, 1 / 2), (BANELING, 2 / 1), (ZERGLING, 2 / 1), (LURKERMP, 1 / 5),
                        (INFESTOR, 1 / 10)],
            HYDRALISKBURROWED: [(OVERSEER, 1 / 10), (BROODLORD, 1 / 2), (BANELING, 2),
                                (ZERGLING, 2), (LURKERMP, 1 / 5), (INFESTOR, 1 / 10)],
            MUTALISK: [(HYDRALISK, 1), (CORRUPTOR, 1 / 2), (INFESTOR, 1 / 15), (VIPER, 1 / 15)],
            ULTRALISK: [(BROODLORD, 1), (HYDRALISK, 3), (LURKERMP, 3 / 2)],
            ULTRALISKBURROWED: [(OVERSEER, 1 / 5), (BROODLORD, 1), (HYDRALISK, 3), (LURKERMP, 3 / 2)],
            ROACH: [(ROACH, 1), (RAVAGER, 1 / 5)],
            ROACHBURROWED: [(OVERSEER, 1 / 10), (ROACH, 1), (RAVAGER, 1 / 5)],
            INFESTOR: [(ULTRALISK, 1 / 3), (OVERSEER, 1 / 5), (BROODLORD, 1 / 2)],
            OVERSEER: [(HYDRALISK, 1), (CORRUPTOR, 1)],
            RAVAGER: [(ROACH, 1), (RAVAGER, 1 / 2)],
            LURKERMP: [(VIPER, 1 / 3), (OVERSEER, 1 / 2), (LURKERMP, 1)],
            LURKERMPBURROWED: [(VIPER, 1 / 3), (OVERSEER, 1 / 2), (LURKERMP, 1)],
            CORRUPTOR: [(CORRUPTOR, 1 / 1), (HYDRALISK, 1 / 1)],
            VIPER: [(CORRUPTOR, 3 / 2)],
            BROODLORD: [(VIPER, 1 / 1), (HYDRALISK, 4 / 1), (CORRUPTOR, 2 / 1)],
            SPINECRAWLER: [(RAVAGER, 1 / 1)],
            SPINECRAWLERUPROOTED: [(RAVAGER, 1 / 1)],
            SPORECRAWLER: [(RAVAGER, 1 / 1)],
            SPORECRAWLERUPROOTED: [(RAVAGER, 1 / 1)],
            OVERLORDTRANSPORT: [(HYDRALISK, 1 / 4)],
            CREEPTUMOR: [(OVERSEER, 1 / 50)],
            CREEPTUMORBURROWED: [(OVERSEER, 1 / 50)],
            SWARMHOSTMP: [(VIPER, 1 / 2), (BROODLORD, 1 / 2)],
            SWARMHOSTBURROWEDMP: [(VIPER, 1 / 2), (BROODLORD, 1 / 2)],

            # Protoss
            ZEALOT: [(ROACH, 1 / 1), (BROODLORD, 1 / 10), (BANELING, 2 / 1), (ULTRALISK, 1 / 10), (LURKER, 1 / 3)],
            STALKER: [(HYDRALISK, 1 / 1), (ZERGLING, 2 / 1), (BANELING, 2 / 1)],
            ADEPT: [(ROACH, 1 / 1), (BANELING, 2 / 1)],
            SENTRY: [(RAVAGER, 1 / 1), (ULTRALISK, 1 / 5), (BROODLORD, 1 / 5), (ZERGLING, 2 / 1)],
            IMMORTAL: [(ZERGLING, 5 / 1), (HYDRALISK, 3 / 1), (BANELING, 1 / 1), (BROODLORD, 1 / 3)],
            WARPPRISM: [(HYDRALISK, 1 / 1), (CORRUPTOR, 1 / 2)],
            WARPPRISMPHASING: [(HYDRALISK, 1 / 1), (CORRUPTOR, 1 / 2)],
            VOIDRAY: [(HYDRALISK, 2 / 1), (CORRUPTOR, 1 / 1)],
            PHOENIX: [(HYDRALISK, 3 / 2), (CORRUPTOR, 1 / 2)],
            COLOSSUS: [(BROODLORD, 1 / 1), (ULTRALISK, 1 / 1), (CORRUPTOR, 2 / 1), (VIPER, 1 / 2)],
            TEMPEST: [(CORRUPTOR, 2 / 1), (VIPER, 1 / 2)],
            HIGHTEMPLAR: [(BROODLORD, 1 / 2), (ROACH, 2 / 1), (ULTRALISK, 1 / 5)],
            DISRUPTOR: [(BROODLORD, 1 / 2), (VIPER, 1 / 2)],
            DARKTEMPLAR: [(OVERSEER, 1 / 2), (BROODLORD, 1 / 4)],
            OBSERVER: [(HYDRALISK, 1 / 1)],
            ARCHON: [(BROODLORD, 1 / 2), (SWARMHOSTMP, 1 / 1)],
            ORACLE: [(CORRUPTOR, 1 / 1)],
            CARRIER: [(CORRUPTOR, 2 / 1), (VIPER, 1 / 1)],
            MOTHERSHIP: [(CORRUPTOR, 5 / 1), (VIPER, 2 / 1)],
        }
